/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CubeF2l: typeof import('./src/components/cube-f2l.vue')['default']
    CubeOll: typeof import('./src/components/cube-oll.vue')['default']
    CubeTutorial: typeof import('./src/components/cube-tutorial.vue')['default']
    HeadBar: typeof import('./src/components/head-bar.vue')['default']
    ICfopLogo: typeof import('~icons/cfop/logo')['default']
    IMingcuteGithubLine: typeof import('~icons/mingcute/github-line')['default']
    IMingcuteQuestionFill: typeof import('~icons/mingcute/question-fill')['default']
    IMingcuteRefresh4Line: typeof import('~icons/mingcute/refresh4-line')['default']
    IMingcuteTwitterLine: typeof import('~icons/mingcute/twitter-line')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
